#!/bin/bash
#------------------------------------------------------------
# Description: Linux Lite Removal Dialogue
# Author: Jerry Bezencon 2014
# Website: https://www.linuxliteos.com
#------------------------------------------------------------

# Main window dialogue.
 INSTALLER_TITLE="XBMC Media Center Remover
-----------------------------------------------------------------------------------------------------
This will remove the XBMC Media Center.

Please make sure the application has been closed before you proceed.

When you click on Yes, this window will close and the process will begin.

-----------------------------------------------------------------------------------------------------
Click on Yes to continue or No to cancel the removal process."

# Call the zenity window icon location.
 INSTALL_ICON="/usr/share/icons/zenity-llcc.png"
 APPNAME="XBMC"
        
        zenity --question --title="$APPNAME Remover" --window-icon="${INSTALL_ICON}" --text="${INSTALLER_TITLE}"

                if [ "$?" -eq "0" ]; then
                        sudo apt-get remove -f xbmc --force-yes -y | zenity --progress --title="Removing $APPNAME" --window-icon="${INSTALL_ICON}" --text="Please wait whilst $APPNAME uninstalls..." --pulsate --width=400 --auto-close --auto-kill


                                if [ "${PIPESTATUS[0]}" -ne "0" ]; then
                        
                                        zenity --error \
                                        --title="Error" --text="$APPNAME could not be removed."
                                        exit 0 &
                                fi

                else

                                        exit 0
                fi


zenity --info --title="$APPNAME Remover" --window-icon=/usr/share/icons/zenity-llcc.png --text="$APPNAME has been uninstalled."

exit 0
