#! /bin/bash
#--------------------------------------------------------------------------------------------------------
# Name: Linux Lite Additional Software Install 64bit
# Version: 1.0-0210
# Description: A GUI tool to easily install additional software in Linux Lite.
# Authors: Misko_2083, Jerry Bezencon
# Date: September 26th, 2014
# Website: https://www.linuxliteos.com
#--------------------------------------------------------------------------------------------------------

# Dialog icon
ic="/usr/share/icons/zenity-llcc.png"

# Check if Apple Trailers Plugin is installed
test_installed=( `apt-cache policy  totem-mozilla ubuntu-restricted-extras| grep "Installed:"` )
if [ "${test_installed[1]}" != "(none)" ];then
  appletrailers=("FALSE" "Apple Trailers Plugin" "Internet" "Installed" "Watch Apple trailers in your web browser (Firefox only)" )
else
  appletrailers=("FALSE" "Apple Trailers Plugin" "Internet" "Not Installed" "Watch Apple trailers in your web browser (Firefox only)" )
fi

# Check if Chrome Web Browser is installed
if [ `builtin type -p google-chrome-stable` ];then
  googlechromebr=("FALSE" "Chrome Web Browser" "Internet" "Installed" "Install the Google Chrome web browser" )
else
  googlechromebr=("FALSE" "Chrome Web Browser" "Internet" "Not Installed" "Install the Google Chrome web browser" )
fi

# Check if Chromium Web Browser is installed
if [ `builtin type -p chromium-browser` ];then
  chromiumbr=("FALSE" "Chromium Web Browser" "Internet" "Installed" "Install the open-source alternative to the Google Chrome web browser" )
else
  chromiumbr=("FALSE" "Chromium Web Browser" "Internet" "Not Installed" "Install the open-source alternative to the Google Chrome web browser" )
fi

# Check if Dropbox is installed
if [ `builtin type -p dropbox` ];then
  dropbox=("FALSE" "Dropbox" "Internet" "Installed" "A popular cloud storage application" )
else
  dropbox=("FALSE" "Dropbox" "Internet" "Not Installed" "A popular cloud storage application" )
fi

# Check if File & Folder Search (catfish) is installed
if [ `builtin type -p catfish` ];then
  catfish=("FALSE" "File & Folder Search" "Accessories" "Installed" "Easily locate files and folders in your computer" )
else
  catfish=("FALSE" "File & Folder Search" "Accessories" "Not Installed" "Easily locate files and folders in your computer" )
fi

# Check if Games Pack is installed
if [ `builtin type -p aisleriot mahjongg glchess gnomine gnome-hearts` ];then
  gamespack=("FALSE" "Games Pack" "Games" "Installed" "Comes with Solitaire, Chess, Mahjongg, Mines and Hearts" )
else
  gamespack=("FALSE" "Games Pack" "Games" "Not Installed" "Comes with Solitaire, Chess, Mahjongg, Mines and Hearts" )
fi

# Check if Google Talk is installed
test_installed=( `apt-cache policy google-talkplugin| grep "Installed:"` )
if [ "${test_installed[1]}" != "(none)" ];then
  googletalk=("FALSE" "Google Talk Browser Plugin" "Internet" "Installed" "Install this plugin to use Google Hangouts video chat" )
else
  googletalk=("FALSE" "Google Talk Browser Plugin" "Internet" "Not Installed" "Install this plugin to use Google Hangouts video chat" )
fi

# Check if iDevices Manager (gtkpod) is installed
if [ `builtin type -p gtkpod` ];then
  idevices=("FALSE" "iDevices Manager" "Multimedia" "Installed" "Manage your iDevices with Gtkpod" )
else
  idevices=("FALSE" "iDevices Manager" "Multimedia" "Not Installed" "Manage your iDevices with Gtkpod" )
fi

# Check if Instant Messenger (pidgin) is installed
if [ `builtin type -p pidgin` ];then
  imessenger=("FALSE" "Instant Messenger" "Internet" "Installed" "This will install Pidgin, a multi-protocol Instant Messenging client" )
else
  imessenger=("FALSE" "Instant Messenger" "Internet" "Not Installed" "This will install Pidgin, a multi-protocol Instant Messenging client" )
fi

# Check if Java Web Applet Plugin is installed
test_installed=( `apt-cache policy icedtea-7-plugin | grep "Installed:"` )
if [  "${test_installed[1]}" != "(none)" ];then
  javaplugin=("FALSE" "Java Web Applet Plugin" "Internet" "Installed" "To allow you to view java applets in your web browser" )
else
  javaplugin=("FALSE" "Java Web Applet Plugin" "Internet" "Not Installed" "To allow you to view java applets in your web browser" )
fi

# Check if Netflix is installed
if [ `builtin type -p netflix-desktop` ];then
  netflix=("FALSE" "Netflix" "Multimedia" "Installed" "A popular streaming tv and movie service (account required)" )
else
  netflix=("FALSE" "Netflix" "Multimedia" "Not Installed" "A popular streaming tv and movie service (account required)" )
fi

# Check if Password Manager (KeePassX) is installed
if [ `builtin type -p keepassx` ];then
  passmgr=("FALSE" "Password Manager" "Accessories" "Installed" "Installs KeePassX, an excellent password manager" )
else
  passmgr=("FALSE" "Password Manager" "Accessories" "Not Installed" "Installs KeePassX, an excellent password manager" )
fi

# Check if Playonlinux is installed
if [ `builtin type -p playonlinux` ];then
  playonlinux=("FALSE" "PlayOnLinux" "Cross Platform" "Installed" "Easily install and use numerous games and apps designed to run with Windows" )
else
  playonlinux=("FALSE" "PlayOnLinux" "Cross Platform" "Not Installed" "Easily install and use numerous games and apps designed to run with Windows" )
fi

# Check if Remote Desktop Software (Remina) is installed
if [ `builtin type -p remmina` ];then
  remote=("FALSE" "Remote Desktop Software" "Internet" "Installed" "Installs the Remmina Remote Desktop Client for Windows (RDP) and VNC Servers" )
else
  remote=("FALSE" "Remote Desktop Software" "Not Installed" "Internet" "Installs the Remmina Remote Desktop Client for Windows (RDP) and VNC Servers" )
fi

# Check if Restricted Extras are installed
test_installed=( `apt-cache policy  ubuntu-restricted-extras libavcodec-extra | grep "Installed:"` )
if [ "${test_installed[1]}" != "(none)" ];then
  extras=("FALSE" "Restricted Extras" "Multimedia" "Installed" "Installs additional codecs and useful file formats that are not shipped by default" )
else
  extras=("FALSE" "Restricted Extras" "Multimedia" "Not Installed" "Installs additional codecs and useful file formats that are not shipped by default" )
fi

# Check if Skype is installed
if [ `builtin type -p skype` ];then
  skype=("FALSE" "Skype" "Internet" "Installed" "A popular audio and video chat application" )
else
  skype=("FALSE" "Skype" "Internet" "Not Installed" "A popular audio and video chat application" )
  
fi

# Check if Steam is installed
if [ `builtin type -p steam` ];then
  steam=("FALSE" "Steam" "Games" "Installed" "Steam is a cross platform gaming client" )
else
  steam=("FALSE" "Steam" "Games" "Not Installed" "Steam is a cross platform gaming client" )
fi

# Check if Teamviewer is installed
if [ `builtin type -p teamviewer` ];then
  teamviewer=("FALSE" "Teamviewer" "Internet" "Installed" "Installs Teamviewer Remote Desktop Support software" )
else
  teamviewer=("FALSE" "Teamviewer" "Internet" "Not Installed" "Installs Teamviewer Remote Desktop Support software" )
fi

# Check if Torrent Software is installed
if [ `builtin type -p deluge` ];then
  torrent=("FALSE" "Torrent Software" "Internet" "Installed" "Installs the Deluge Torrent client software" )
else
  torrent=("FALSE" "Torrent Software" "Internet" "Not Installed" "Installs the Deluge Torrent client software" )
fi

# Check if Video Editing Software is installed
if [ `builtin type -p "openshot %" blender libavformat-extra-54` ];then
  videoedit=("FALSE" "Video Editing Software" "Multimedia" "Installed" "Installs Openshot, a simple to use yet powerful video editor for linux" )
else
  videoedit=("FALSE" "Video Editing Software" "Multimedia" "Not Installed" "Installs Openshot, a simple to use yet powerful video editor for linux" )
fi

# Check if Virtualbox is installed
if [ `builtin type -p virtualbox` ];then
  vbox=("FALSE" "VirtualBox" "System" "Installed" "Virtualbox - install other operating systems like Windows from within Linux Lite" )
else
  vbox=("FALSE" "VirtualBox" "System" "Not Installed" "Virtualbox - install other operating systems like Windows from within Linux Lite" )
fi

# Check if Weather Monitor is installed
test_installed=( `apt-cache policy  xfce4-weather-plugin| grep "Installed:"` )
if [ "${test_installed[1]}" != "(none)" ];then
  weather=("FALSE" "Weather Monitor" "System Tray" "Installed" "This will install a Weather Monitor Plugin for your tray" )
else
  weather=("FALSE" "Weather Monitor" "System Tray" "Not Installed" "This will install a Weather Monitor Plugin for your tray" )
fi

# Check if Guvcview is installed
if [ `builtin type -p guvcview` ];then
  guvcview=("FALSE" "Webcam Software" "Internet" "Installed" "Guvcview, webcam software for your computer" )
else
  guvcview=("FALSE" "Webcam Software" "Internet" "Not Installed" "Guvcview, webcam software for your computer" )
fi

# Check if Wine is installed
if [ `builtin type -p wine` ];then
  wine=("FALSE" "Wine" "Cross Platform" "Installed" "Wine - install and run some Windows programs and games on Linux Lite" )
else
  wine=("FALSE" "Wine" "Cross Platform" "Not Installed" "Wine - install and run some Windows programs and games on Linux Lite" )
fi

# Check if XBMC Media Center is installed
if [ `builtin type -p xbmc` ];then
  xbmc=("FALSE" "XBMC" "Multimedia" "Installed" "This will install the XBMC Media Center" )
else
  xbmc=("FALSE" "XBMC" "Multimedia" "Not Installed" "This will install the XBMC Media Center" )
fi

# Dialog window
selection=$(zenity --window-icon="$ic" --list --checklist --width=900 --height=720 --column="Select" --column="Name" --column="Category" --column="Status" \
  --column="Description" --text="Select the program you wish to install, then click the Install button. Sort Categories by clicking on the column.\nYou can select multiple programs to install." --title="Install Additional Software" --ok-label="Install" --cancel-label="Quit" \
  "${appletrailers[@]}" \
  "${googlechromebr[@]}" \
  "${chromiumbr[@]}" \
  "${dropbox[@]}" \
  "${catfish[@]}" \
  "${gamespack[@]}" \
  "${googletalk[@]}" \
  "${idevices[@]}" \
  "${imessenger[@]}" \
  "${javaplugin[@]}" \
  "${netflix[@]}" \
  "${passmgr[@]}" \
  "${playonlinux[@]}" \
  "${remote[@]}" \
  "${extras[@]}" \
  "${skype[@]}" \
  "${steam[@]}" \
  "${teamviewer[@]}" \
  "${torrent[@]}" \
  "${videoedit[@]}" \
  "${vbox[@]}" \
  "${weather[@]}" \
  "${guvcview[@]}" \
  "${wine[@]}" \
"${xbmc[@]}" )

# If Quit is clicked then exit
if [ "${PIPESTATUS[0]}" -ne "0" ]; then
  exit 0
fi

# Check if anything is selected
echo $selection | grep '[a-zA-Z0-9]'
if [  "${PIPESTATUS[1]}" -ne "0" ]; then
  zenity --info --title='Install Additional Software' --text='Nothing was selected for installation.'
  exit 0
fi

# Script exec
echo $selection | grep "Apple Trailers Plugin" > /dev/null
if [ $? = 0 ];then
  /usr/scripts/trailers 2>/dev/null
fi

echo $selection | grep "Chrome Web Browser" > /dev/null
if [ $? = 0 ];then
  /usr/scripts/chrome 2>/dev/null
fi

echo $selection | grep "Chromium Web Browser" > /dev/null
if [ $? = 0 ];then
  /usr/scripts/chromium 2>/dev/null
fi

echo $selection | grep "Dropbox" > /dev/null
if [ $? = 0 ];then
  /usr/scripts/dropbox 2>/dev/null
fi

echo $selection | grep "File & Folder Search" > /dev/null
if [ $? = 0 ];then
  /usr/scripts/search 2>/dev/null
fi

echo $selection | grep "Games Pack" > /dev/null
if [ $? = 0 ];then
  /usr/scripts/games 2>/dev/null
fi

echo $selection | grep "Google Talk Browser Plugin" > /dev/null
if [ $? = 0 ];then
  /usr/scripts/googletalk 2>/dev/null
fi

echo $selection | grep "iDevices Manager" > /dev/null
if [ $? = 0 ];then
  /usr/scripts/idev 2>/dev/null
fi

echo $selection | grep "Instant Messenger" > /dev/null
if [ $? = 0 ];then
  /usr/scripts/im 2>/dev/null
fi

echo $selection | grep "Java Web Applet Plugin" > /dev/null
if [ $? = 0 ];then
  /usr/scripts/javaplugin 2>/dev/null
fi

echo $selection | grep "Netflix" > /dev/null
if [ $? = 0 ];then
  /usr/scripts/netflix 2>/dev/null
fi

echo $selection | grep "Password Manager" > /dev/null
if [ $? = 0 ];then
  /usr/scripts/keepassx 2>/dev/null
fi

echo $selection | grep "PlayOnLinux" > /dev/null
if [ $? = 0 ];then
  /usr/scripts/playonlinux 2>/dev/null
fi

echo $selection | grep "Remote Desktop Software" > /dev/null
if [ $? = 0 ];then
  /usr/scripts/remote 2>/dev/null
fi

echo $selection | grep "Restricted Extras" > /dev/null
if [ $? = 0 ];then
  /usr/scripts/re 2>/dev/null
fi

echo $selection | grep "Skype" > /dev/null
if [ $? = 0 ];then
  /usr/scripts/skype 2>/dev/null
fi

echo $selection | grep "Steam" > /dev/null
if [ $? = 0 ];then
  /usr/scripts/steam64 2>/dev/null
fi

echo $selection | grep "Teamviewer" > /dev/null
if [ $? = 0 ];then
  /usr/scripts/teamviewer 2>/dev/null
fi

echo $selection | grep "Torrent Software" > /dev/null
if [ $? = 0 ];then
  /usr/scripts/deluge 2>/dev/null
fi

echo $selection | grep "Video Editing Software" > /dev/null
if [ $? = 0 ];then
  /usr/scripts/openshot 2>/dev/null
fi

echo $selection | grep "VirtualBox" > /dev/null
if [ $? = 0 ];then
  /usr/scripts/virtualbox 2>/dev/null
fi

echo $selection | grep "Weather Monitor" > /dev/null
if [ $? = 0 ];then
  /usr/scripts/weather 2>/dev/null
fi

echo $selection | grep "Webcam Software" > /dev/null
if [ $? = 0 ];then
  /usr/scripts/guvcview 2>/dev/null
fi

echo $selection | grep "Wine" > /dev/null
if [ $? = 0 ];then
  /usr/scripts/wine 2>/dev/null
fi

echo $selection | grep "XBMC" > /dev/null
if [ $? = 0 ];then
  /usr/scripts/xbmc 2>/dev/null
fi
