#!/bin/bash
#------------------------------------------------------------
# Description: Linux Lite Removal Dialogue
# Author: Jerry Bezencon 2014
# Website: https://www.linuxliteos.com
#------------------------------------------------------------

# Main window dialogue.
 INSTALLER_TITLE="Games Pack Remover
-----------------------------------------------------------------------------------------------------------
This will remove the Linux Lite Games Pack.

Please make sure the applications have been closed before you proceed.

When you click on Yes, this window will close and the process will begin.

-----------------------------------------------------------------------------------------------------------
Click on Yes to continue or No to cancel the removal process."

# Call the zenity window icon location.
 INSTALL_ICON="/usr/share/icons/zenity-llcc.png"
 APPNAME="Games Pack"
        
		test_gamespack1=(`apt-cache policy aisleriot | grep "Installed:"`)
		test_gamespack2=(`apt-cache policy mahjongg | grep "Installed:"`)
		test_gamespack3=(`apt-cache policy glchess | grep "Installed:"`)
		test_gamespack4=(`apt-cache policy gnomine | grep "Installed:"`)
		test_gamespack5=(`apt-cache policy gnome-hearts | grep "Installed:"`)
		if [ "${test_gamespack1[1]}" == "(none)" ] && [ "${gamespack2[1]}" == "(none)" ] && [ "${test_gamespack3[1]}" == "(none)" ] && [ "${test_gamespack4[1]}" == "(none)" ] && [ "${test_gamespack5[1]}" == "(none)" ];then
			zenity --info --title="$APPNAME Installer" --window-icon="${INSTALL_ICON}" --text="$APPNAME is already installed."
 			exit 0
		fi


        zenity --question --title="$APPNAME Remover" --window-icon="${INSTALL_ICON}" --text="${INSTALLER_TITLE}"

                if [ "$?" -eq "0" ]; then
                        sudo apt-get remove -f aisleriot mahjongg glchess gnomine gnome-hearts --force-yes -y | zenity --progress --title="Removing $APPNAME" --window-icon="${INSTALL_ICON}" --text="Please wait whilst $APPNAME uninstalls..." --pulsate --width=400 --auto-close --auto-kill


                                if [ "${PIPESTATUS[0]}" -ne "0" ]; then
                        
                                        zenity --error \
                                        --title="Error" --text="$APPNAME could not be removed."
                                        exit 0 &
                                fi

                else

                                        exit 0
                fi


zenity --info --title="$APPNAME Remover" --window-icon=/usr/share/icons/zenity-llcc.png --text="$APPNAME has been uninstalled."

exit 0
