#!/bin/bash
#-------------------------------------------
# Description: Linux Lite Installer Dialogue
# Author: Jerry Bezencon 2014
# Website: https://www.linuxliteos.com
#-------------------------------------------

# Main window dialogue.
 INSTALLER_TITLE="Netflix Installer
-------------------------------------------------------------------------------------------------------------------
This will install Netflix on your computer. Netflix currently only runs
in the Google Chrome Web Browser so this installation process will install the
Google Chrome Web Browser.

If you already have the Google Chrome Web Browser installed, cancel
this installation now and head over to https://ww.netflix.com/ to start
using Netflix on Linux Lite.

When you click on Yes, this window will close and the install will begin.
The install time will vary based on your internet connection and computer.
Support is available from - https://help.netflix.com/

The Netflix website will launch in Chrome at the conclusion of this installation.
Please remember to add Netflix as a Bookmark.
-------------------------------------------------------------------------------------------------------------------
Click on Yes to continue or No to cancel the installation."

# Call the zenity window icon location.
 INSTALL_ICON="/usr/share/icons/zenity-llcc.png"
 APPNAME="Netflix"
        
        zenity --question --title="$APPNAME Installer" --window-icon="${INSTALL_ICON}" --text="${INSTALLER_TITLE}"

                if [ "$?" -eq "0" ]; then
x=$( stdbuf -oL /bin/bash \-c '(sudo apt-get update && sudo apt-get install google-chrome-stable libnss3 \-y )' 2>&1 |
stdbuf -oL sed -n -e '/\[*$/ s/^/# /p' -e '/\*$/ s/^/# /p'|
zenity --progress --title="Updating System and installing Google Chrome Web Browser..." --pulsate \
--width=600 --auto-close )

                                if [ "${PIPESTATUS[0]}" -ne "0" ]; then
                        
                                        zenity --error \
                                        --title="Error" --text="$APPNAME could not be installed."
                                        exit 0
                                fi

                else

                                        exit 0
                fi


PROCEED=$(zenity --info --title="$APPNAME Installer" --window-icon=/usr/share/icons/zenity-llcc.png --text="Install Complete.\n\nClick on OK to launch Netflix."; echo $?)
if [ ${PROCEED} -eq 1 ]; then
	zenity --info --title="Finished" --window-icon="${INSTALL_ICON}" --text="Install Complete.\n\nClick on OK to launch Netflix"
	exit;
else
	sudo -u '#1000' -H sh -c "google-chrome-stable http://www.netflix.com"

fi

exit 0
