#!/bin/bash
#------------------------------------------------------------
# Description: Linux Lite Installer Dialogue
# Author: Jerry Bezencon 2013
# Website: https://www.linuxliteos.com
#------------------------------------------------------------

# Ensure multi-language support
export LANG=C

# Main window dialogue.
 INSTALLER_TITLE="Pidgin Instant Messenger Installer
-----------------------------------------------------------------------------------------------------
This will install Pidgin, a multi-protocol Instant Messenging client.

Pidgin allows you to chat with your friends on networks such as:
AIM, MSN, ICQ, Yahoo! and many more.

When you click on Yes, this window will close and the install will begin.
The install time will vary based on your internet connection and computer.
Support is available from - https://www.pidgin.im/

Once installed, Pidgin is located in Menu, Internet.
-----------------------------------------------------------------------------------------------------
Click on Yes to continue or No to cancel the installation."

# Call the zenity window icon location.
 INSTALL_ICON="/usr/share/icons/zenity-llcc.png"
 APPNAME="Pidgin"
        
	test_pidgin=(`dpkg -l "pidgin" 2>&1 | grep "^.i" >/dev/null; echo $?`)
		if [ "${test_pidgin[@]}" -eq "0" ];then
			zenity --info --title="$APPNAME Installer" --window-icon="${INSTALL_ICON}" --text="$APPNAME is already installed."
 			exit 0
		fi


        zenity --question --title="$APPNAME Installer" --window-icon="${INSTALL_ICON}" --text="${INSTALLER_TITLE}"

                if [ "$?" -eq "0" ]; then
                        sudo apt-get install -f pidgin --force-yes -y | zenity --progress --title="Installing $APPNAME" --window-icon="${INSTALL_ICON}" --text="Please wait whilst $APPNAME downloads and installs..." --pulsate --width=400 --auto-close --auto-kill


                                if [ "${PIPESTATUS[0]}" -ne "0" ]; then
                        
                                        zenity --error \
                                        --title="Error" --text="$APPNAME could not be installed."
                                        exit 0
                                fi

                else

                                        exit 0
                fi


PROCEED=$(zenity --info --title="$APPNAME Installer" --window-icon=/usr/share/icons/zenity-llcc.png --text="The installation has finished.\n$APPNAME is located in Menu, Internet."; echo $?)
if [ ${PROCEED} -eq 1 ]; then
	zenity --info --title="Finished" --window-icon="${INSTALL_ICON}" --text="Install Complete.\n\n$APPNAME is located in Menu, Internet"
	exit;
else
	exit &
fi

exit 0
