#!/bin/bash
#------------------------------------------------------------
# Description: Linux Lite Installer Dialogue
# Author: Jerry Bezencon 2013
# Website: https://www.linuxliteos.com
#------------------------------------------------------------

# Ensure multi-language support
export LANG=C

# Main window dialogue.
 INSTALLER_TITLE="Apple Trailers Plugin Installer
-----------------------------------------------------------------------------------------------------
This will install the Apple Trailers Plugin for your web browser.

When you click on Yes, this window will close and the install will begin.
The install time will vary based on your internet connection and computer.
Trailers can be viewed at - http://trailers.apple.com/trailers/

Please close any open web browsers now or the program can do it for you.

-----------------------------------------------------------------------------------------------------
Click on Yes to continue or No to cancel the installation."

# Call the zenity window icon location.
 INSTALL_ICON="/usr/share/icons/zenity-llcc.png"
 APPNAME="Apple Trailers Plugin"
        
	test_appletrailers1=(`dpkg -l "totem-mozilla" 2>&1 | grep "^.i" >/dev/null; echo $?`)
	test_appletrailers2=(`dpkg -l "ubuntu-restricted-extras" 2>&1 | grep "^.i" >/dev/null; echo $?`)
		if [ "${test_appletrailers1[@]}" -eq "0" ] && [ "${test_appletrailers2[@]}" -eq "0" ];then
			zenity --info --title="$APPNAME Installer" --window-icon="${INSTALL_ICON}" --text="$APPNAME is already installed."
 			exit 0
		fi


        zenity --question --title="$APPNAME Installer" --window-icon="${INSTALL_ICON}" --text="${INSTALLER_TITLE}"

                if [ "$?" -eq "0" ]; then
                        sudo apt-get install -f totem-mozilla ubuntu-restricted-extras --force-yes -y | zenity --progress --title="Installing $APPNAME" --window-icon="${INSTALL_ICON}" --text="Please wait whilst $APPNAME downloads and installs..." --pulsate --width=400 --auto-close --auto-kill


                                if [ "${PIPESTATUS[0]}" -ne "0" ]; then
                        
                                        zenity --error \
                                        --title="Error" --text="$APPNAME could not be installed."
                                        exit 0
                                fi

                else

                                        exit 0
                fi

PROCEED=$(zenity --info --title="$APPNAME Installer" --window-icon=/usr/share/icons/zenity-llcc.png --text="The installation has finished."; echo $?)
if [ ${PROCEED} -eq 1 ]; then
	zenity --info --title="Finished" --window-icon="${INSTALL_ICON}" --text="Install Complete."
	exit;
else
	exit &
fi

exit 0
