#!/bin/bash
#------------------------------------------------------------
# Description: Linux Lite Installer Dialogue
# Author: Jerry Bezencon 2013
# Website: https://www.linuxliteos.com
#------------------------------------------------------------

# Ensure multi-language support
export LANG=C

# Main window dialogue.
 INSTALLER_TITLE="Virtualbox Installer
-----------------------------------------------------------------------------------------------------
This will install Virtualbox.
Virtualbox allows you to install other operating systems like Windows
from within Linux Lite.

When you click on Yes, this window will close and the install will begin.
The install time will vary based on your internet connection and computer.
Support is available from - https://www.virtualbox.org/

Once installed, Virtualbox is located in Menu, System.
-----------------------------------------------------------------------------------------------------
Click on Yes to continue or No to cancel the installation."

# Call the zenity window icon location.
 INSTALL_ICON="/usr/share/icons/zenity-llcc.png"
 APPNAME="Virtualbox"
        
	test_virtualbox=(`dpkg -l "virtualbox" 2>&1 | grep "^.i" >/dev/null; echo $?`)
		if [ "${test_virtualbox[@]}" -eq "0" ];then
			zenity --info --title="$APPNAME Installer" --window-icon="${INSTALL_ICON}" --text="$APPNAME is already installed."
 			exit 0
		fi


        zenity --question --title="$APPNAME Installer" --window-icon="${INSTALL_ICON}" --text="${INSTALLER_TITLE}"

                if [ "$?" -eq "0" ]; then
                        sudo apt-get install -f virtualbox --force-yes -y | zenity --progress --title="Installing $APPNAME" --window-icon="${INSTALL_ICON}" --text="Please wait whilst $APPNAME downloads and installs..." --pulsate --width=400 --auto-close --auto-kill


                                if [ "${PIPESTATUS[0]}" -ne "0" ]; then
                        
                                        zenity --error \
                                        --title="Error" --text="$APPNAME could not be installed."
                                        exit 0
                                fi

                else

                                        exit 0
                fi


PROCEED=$(zenity --info --title="$APPNAME Installer" --window-icon=/usr/share/icons/zenity-llcc.png --text="The installation has finished.\n$APPNAME is located in Menu, System."; echo $?)
if [ ${PROCEED} -eq 1 ]; then
	zenity --info --title="Finished" --window-icon="${INSTALL_ICON}" --text="Install Complete.\n\n$APPNAME is located in Menu, System"
	exit;
else
	exit &
fi

exit 0
