#!/bin/bash
#-------------------------------------------------------------
# Description: Linux Lite Removal Dialogue
# Author: Jerry Bezencon 2013
# Website: https://www.linuxliteos.com
#-------------------------------------------------------------

# Ensure multi-language support
export LANG=C

# Main window dialogue.
 INSTALLER_TITLE="Games Pack Remover
-----------------------------------------------------------------------------------------------------------
This will remove the Linux Lite Games Pack.

Please make sure the applications have been closed before you proceed.

When you click on Yes, this window will close and the process will begin.

-----------------------------------------------------------------------------------------------------------
Click on Yes to continue or No to cancel the removal process."

# Call the zenity window icon location.
 INSTALL_ICON="/usr/share/icons/zenity-llcc.png"
 APPNAME="Games Pack"
        
		test_gamespack1=(`dpkg -l "aisleriot" 2>&1 | grep "^.i" >/dev/null; echo $?`)
		test_gamespack2=(`dpkg -l "gnome-mahjongg" 2>&1 | grep "^.i" >/dev/null; echo $?`)
		test_gamespack3=(`dpkg -l "gnome-chess" 2>&1 | grep "^.i" >/dev/null; echo $?`)
		test_gamespack4=(`dpkg -l "gnome-mines" 2>&1 | grep "^.i" >/dev/null; echo $?`)
		test_gamespack5=(`dpkg -l "gnome-hearts" 2>&1 | grep "^.i" >/dev/null; echo $?`)
		if [ "${test_gamespack1[@]}" -eq "1" ] && [ "${gamespack2[@]}" -eq "1" ] && [ "${test_gamespack3[@]}" -eq "1" ] && [ "${test_gamespack4[@]}" -eq "1" ] && [ "${test_gamespack5[@]}" -eq "1" ];then
			zenity --info --title="$APPNAME Installer" --window-icon="${INSTALL_ICON}" --text="$APPNAME is already removed."
 			exit 0
		fi

        zenity --question --title="$APPNAME Remover" --window-icon="${INSTALL_ICON}" --text="${INSTALLER_TITLE}"

                if [ "$?" -eq "0" ]; then
                        sudo apt-get remove -f aisleriot gnome-mahjongg gnome-chess gnome-mines gnome-hearts --force-yes -y | zenity --progress --title="Removing $APPNAME" --window-icon="${INSTALL_ICON}" --text="Please wait whilst $APPNAME uninstalls..." --pulsate --width=400 --auto-close --auto-kill

                                if [ "${PIPESTATUS[0]}" -ne "0" ]; then
                        
                                        zenity --error \
                                        --title="Error" --text="$APPNAME could not be removed."
                                        exit 0 &
                                fi

                else

                                        exit 0
                fi

zenity --info --title="$APPNAME Remover" --window-icon=/usr/share/icons/zenity-llcc.png --text="$APPNAME has been uninstalled."

exit 0
