#!/bin/bash
#-------------------------------------------------------------
# Description: Linux Lite Removal Dialogue
# Author: Jerry Bezencon 2013
# Website: https://www.linuxliteos.com
#-------------------------------------------------------------

# Ensure multi-language support
export LANG=C

# Main window dialogue.
 INSTALLER_TITLE="Apple Trailers Plugin Remover
-----------------------------------------------------------------------------------------------------------
This will remove the Apple Trailers Plugin from your web browser.

Please make sure all web browsers have been closed before you proceed.

When you click on Yes, this window will close and the process will begin.

-----------------------------------------------------------------------------------------------------------
Click on Yes to continue or No to cancel the removal process."

# Call the zenity window icon location.
 INSTALL_ICON="/usr/share/icons/zenity-llcc.png"
 APPNAME="Apple Trailers Plugin"
        
	test_appletrailers1=(`apt-cache policy totem-mozilla | grep "Installed:"`)
	test_appletrailers2=(`apt-cache policy ubuntu-restricted-extras | grep "Installed:"`)
		if [ "${test_appletrailers1[1]}" == "(none)" ] && [ "${test_appletrailers2[1]}" == "(none)" ];then
			zenity --info --title="$APPNAME Installer" --window-icon="${INSTALL_ICON}" --text="$APPNAME is already removed."
 			exit 0
		fi

        zenity --question --title="$APPNAME Remover" --window-icon="${INSTALL_ICON}" --text="${INSTALLER_TITLE}"

                if [ "$?" -eq "0" ]; then
                        sudo apt-get remove -f totem-mozilla totem totem-common totem-plugins zeitgeist zeitgeist-core zeitgeist-datahub libzeitgeist-2.0-0 --force-yes -y | zenity --progress --title="Removing $APPNAME" --window-icon="${INSTALL_ICON}" --text="Please wait whilst $APPNAME uninstalls..." --pulsate --width=400 --auto-close --auto-kill

                                if [ "${PIPESTATUS[0]}" -ne "0" ]; then
                        
                                        zenity --error \
                                        --title="Error" --text="$APPNAME could not be removed."
                                        exit 0 &
                                fi

                else

                                        exit 0
                fi

zenity --info --title="$APPNAME Remover" --window-icon=/usr/share/icons/zenity-llcc.png --text="$APPNAME has been uninstalled."

exit 0
