#! /bin/bash
#--------------------------------------------------------------------------------------------------------
# Name: Linux Lite Install Additional Software
# Description: A GUI tool to easily install additional software in Linux Lite.
# Authors: Misko_2083, Jerry Bezencon
# Date: Aug 27th, 2014
# Website: https://www.linuxliteos.com
#--------------------------------------------------------------------------------------------------------

ic="/usr/share/icons/zenity-llcc.png"
selection=$(zenity --window-icon="$ic" --list --width=860 --height=680 --column="#" --column="Name" --column="Category" \
 --column="Description" --text="Click on the program you wish to install, then click the Install button. Sort Categories by clicking on the column." --title="Install Additional Software" --ok-label="Install" --cancel-label="Quit" \
"1" "Apple Trailers Plugin" "Internet" "Watch Apple trailers in your web browser (Firefox only)" \
"2" "Chrome Web Browser" "Internet" "Install the Google Chrome web browser" \
"3" "Chromium Web Browser" "Internet" "Install the open-source alternative to the Google Chrome web browser" \
"4" "Dropbox" "Internet" "A popular cloud storage application" \
"5" "File & Folder Search" "Accessories" "Easily locate files and folders in your computer" \
"6" "Games Pack" "Games" "Comes with Solitaire, Chess, Mahjongg, Mines and Hearts" \
"7" "Google Talk Browser Plugin" "Internet" "Install this plugin to use Google Hangouts video chat" \
"8" "iDevices Manager" "Multimedia" "Manage your iDevices with Gtkpod" \
"9" "Instant Messenger" "Internet" "This will install Pidgin, a multi-protocol Instant Messenging client" \
"10" "Java Web Applet Plugin" "Internet" "To allow you to view java applets in your web browser" \
"11" "Netflix" "Multimedia" "A popular streaming tv and movie service (account required)" \
"12" "Password Manager" "Accessories" "Installs KeePassX, an excellent password manager" \
"13" "PlayOnLinux" "Cross Platform" "Easily install and use numerous games and apps designed to run with Windows" \
"14" "Remote Desktop Software" "Internet" "Installs the Remmina Remote Desktop Client for Windows (RDP) and VNC Servers" \
"15" "Restricted Extras" "Multimedia" "Installs additional codecs and useful file formats that are not shipped by default" \
"16" "Skype" "Internet" "A popular audio and video chat application" \
"17" "Teamviewer" "Internet" "Installs Teamviewer Remote Desktop Support software" \
"18" "Torrent Software" "Internet" "Installs the Deluge Torrent client software" \
"19" "Video Editing Software" "Multimedia" "Installs Openshot, a simple to use yet powerful video editor for linux" \
"20" "VirtualBox" "System" "Virtualbox allows you to install other operating systems like Windows from within Linux Lite" \
"21" "Weather Monitor" "System Tray" "This will install a Weather Monitor Plugin for your tray" \
"22" "Webcam Software" "Internet" "Guvcview, webcam software for your computer" \
"23" "Wine" "Cross Platform" "Wine allows you to install and run some Windows programs and games on Linux Lite" \
"24" "XBMC" "Multimedia" "This will install the XBMC Media Center" )

case "$selection" in
"1")/usr/scripts/trailers 2>/dev/null ;;
"2")/usr/scripts/chrome 2>/dev/null ;;
"3")/usr/scripts/chromium 2>/dev/null ;;
"4")/usr/scripts/dropbox 2>/dev/null ;;
"5")/usr/scripts/search 2>/dev/null ;;
"6")/usr/scripts/games 2>/dev/null ;;
"7")/usr/scripts/googletalk 2>/dev/null ;;
"8")/usr/scripts/idev 2>/dev/null ;;
"9")/usr/scripts/im 2>/dev/null ;;
"10")/usr/scripts/javaplugin 2>/dev/null ;;
"11")/usr/scripts/netflix 2>/dev/null ;;
"12")/usr/scripts/keepassx 2>/dev/null ;;
"13")/usr/scripts/playonlinux 2>/dev/null ;;
"14")/usr/scripts/remote 2>/dev/null ;;
"15")/usr/scripts/re 2>/dev/null ;;
"16")/usr/scripts/skype 2>/dev/null ;;
"17")/usr/scripts/teamviewer 2>/dev/null ;;
"18")/usr/scripts/deluge 2>/dev/null ;;
"19")/usr/scripts/openshot 2>/dev/null ;;
"20")/usr/scripts/virtualbox 2>/dev/null ;;
"21")/usr/scripts/weather 2>/dev/null ;;
"22")/usr/scripts/guvcview 2>/dev/null ;;
"23")/usr/scripts/wine 2>/dev/null ;;
"24")/usr/scripts/xbmc 2>/dev/null ;;
esac
