#!/bin/bash
#-------------------------------------------------------------
# Description: Linux Lite Removal Dialogue
# Author: Jerry Bezencon 2013
# Website: https://www.linuxliteos.com
#-------------------------------------------------------------

# Ensure multi-language support
export LANG=C

# Main window dialogue.
 INSTALLER_TITLE="Java Applet Plugin Remover
-----------------------------------------------------------------------------------------------------
This will remove the Java Applet Plugin from your web browser.

Please make sure the application has been closed before you proceed.

When you click on Yes, this window will close and the process will begin.

-----------------------------------------------------------------------------------------------------
Click on Yes to continue or No to cancel the removal process."

# Call the zenity window icon location.
 INSTALL_ICON="/usr/share/icons/zenity-llcc.png"
 APPNAME="Java Applet Plugin"

        test_icedtea=(`dpkg -l "icedtea-7-plugin" 2>&1 | grep "^.i" >/dev/null; echo $?`)
		if [ "${test_icedtea[@]}" -eq "1" ];then
			zenity --info --title="$APPNAME Installer" --window-icon="${INSTALL_ICON}" --text="$APPNAME is already removed."
 			exit 0
		fi

        zenity --question --title="$APPNAME Remover" --window-icon="${INSTALL_ICON}" --text="${INSTALLER_TITLE}"

                if [ "$?" -eq "0" ]; then
                        sudo apt-get remove -f icedtea-7-plugin --force-yes -y | zenity --progress --title="Removing $APPNAME" --window-icon="${INSTALL_ICON}" --text="Please wait whilst $APPNAME uninstalls..." --pulsate --width=400 --auto-close --auto-kill


                                if [ "${PIPESTATUS[0]}" -ne "0" ]; then
                        
                                        zenity --error \
                                        --title="Error" --text="$APPNAME could not be removed."
                                        exit 0 &
                                fi

                else

                                        exit 0
                fi


zenity --info --title="$APPNAME Remover" --window-icon=/usr/share/icons/zenity-llcc.png --text="$APPNAME has been uninstalled."

exit 0
