#!/bin/bash
#------------------------------------------------------------
# Description: Linux Lite Installer Dialogue
# Author: Jerry Bezencon 2013
# Website: https://www.linuxliteos.com
#------------------------------------------------------------

# Ensure multi-language support
export LANG=C

# Main window dialogue.
 INSTALLER_TITLE="Weather Monitor Plugin Installer
-----------------------------------------------------------------------------------------------------
This will install a Weather Monitor Plugin for your tray.

Once the installation has finished, you will be presented with a set of
instructions to add the Weather Monitor to your tray area.

When you click on Yes, this window will close and the install will begin.
The install time will vary based on your internet connection and computer.
-----------------------------------------------------------------------------------------------------
Click on Yes to continue or No to cancel the installation."

# Call the zenity window icon location.
 INSTALL_ICON="/usr/share/icons/zenity-llcc.png"
 APPNAME="Weather Monitor Plugin"
        
	test_weather=(`apt-cache policy xfce4-weather-plugin | grep "Installed:"`)
		if [ "${test_weather[1]}" != "(none)" ];then
			zenity --info --title="$APPNAME Installer" --window-icon="${INSTALL_ICON}" --text="$APPNAME is already installed."
 			exit 0
		fi

        zenity --question --title="$APPNAME Installer" --window-icon="${INSTALL_ICON}" --text="${INSTALLER_TITLE}"

                if [ "$?" -eq "0" ]; then
                        sudo apt-get install -f xfce4-weather-plugin --force-yes -y | zenity --progress --title="Installing $APPNAME" --window-icon="${INSTALL_ICON}" --text="Please wait whilst $APPNAME downloads and installs..." --pulsate --width=400 --auto-close --auto-kill

                                if [ "${PIPESTATUS[0]}" -ne "0" ]; then
                        
                                        zenity --error \
                                        --title="Error" --text="$APPNAME could not be installed."
                                        exit 0
                                fi

                else

                                        exit 0
                fi

PROCEED=$(echo "The installation has finished. Add the Weather plugin to the taskbar by right clicking on the taskbar select Panel, Add New Items, scroll down to Weather Update highlight and click Add, then Close. Right click on the Weather plugin in the tray and select Properties. And finally, Change your Location." | zenity --title="$APPNAME Installer" --window-icon=/usr/share/icons/zenity-llcc.png --text-info --width=400 --height=200; echo $?)
if [ ${PROCEED} -eq 1 ]; then
	exit;
else
	exit &
fi

exit 0
